# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import simulation_pb2 as simulation__pb2


class SimulationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/simulation.Simulation/Start',
                request_serializer=simulation__pb2.EmptyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.Stop = channel.unary_unary(
                '/simulation.Simulation/Stop',
                request_serializer=simulation__pb2.EmptyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.Pause = channel.unary_unary(
                '/simulation.Simulation/Pause',
                request_serializer=simulation__pb2.EmptyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.CreateBody = channel.unary_unary(
                '/simulation.Simulation/CreateBody',
                request_serializer=simulation__pb2.CreateBodyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.CreatePlayer = channel.unary_unary(
                '/simulation.Simulation/CreatePlayer',
                request_serializer=simulation__pb2.CreatePlayerParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.InitializePopulation = channel.unary_unary(
                '/simulation.Simulation/InitializePopulation',
                request_serializer=simulation__pb2.CreatePopulationParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.UpdateBody = channel.unary_unary(
                '/simulation.Simulation/UpdateBody',
                request_serializer=simulation__pb2.UpdateBodyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )
        self.DeleteBody = channel.unary_unary(
                '/simulation.Simulation/DeleteBody',
                request_serializer=simulation__pb2.DeleteBodyParam.SerializeToString,
                response_deserializer=simulation__pb2.Response.FromString,
                )


class SimulationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlayer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializePopulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBody(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=simulation__pb2.EmptyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=simulation__pb2.EmptyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=simulation__pb2.EmptyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'CreateBody': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBody,
                    request_deserializer=simulation__pb2.CreateBodyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'CreatePlayer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlayer,
                    request_deserializer=simulation__pb2.CreatePlayerParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'InitializePopulation': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializePopulation,
                    request_deserializer=simulation__pb2.CreatePopulationParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'UpdateBody': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBody,
                    request_deserializer=simulation__pb2.UpdateBodyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
            'DeleteBody': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBody,
                    request_deserializer=simulation__pb2.DeleteBodyParam.FromString,
                    response_serializer=simulation__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulation.Simulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/Start',
            simulation__pb2.EmptyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/Stop',
            simulation__pb2.EmptyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/Pause',
            simulation__pb2.EmptyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/CreateBody',
            simulation__pb2.CreateBodyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePlayer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/CreatePlayer',
            simulation__pb2.CreatePlayerParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InitializePopulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/InitializePopulation',
            simulation__pb2.CreatePopulationParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/UpdateBody',
            simulation__pb2.UpdateBodyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteBody(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation.Simulation/DeleteBody',
            simulation__pb2.DeleteBodyParam.SerializeToString,
            simulation__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
