# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bodies.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62odies.proto\x12\x05unary\"Q\n\x0f\x43reateBodyParam\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0b\n\x03p_x\x18\x02 \x01(\x02\x12\x0b\n\x03p_y\x18\x03 \x01(\x02\x12\x0b\n\x03v_x\x18\x04 \x01(\x02\x12\x0b\n\x03v_y\x18\x05 \x01(\x02\"\x1d\n\x0f\x44\x65leteBodyParam\x12\n\n\x02id\x18\x01 \x01(\x05\"\x85\x01\n\x0fUpdateBodyParam\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x03p_x\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x10\n\x03p_y\x18\x03 \x01(\x02H\x01\x88\x01\x01\x12\x10\n\x03v_x\x18\x04 \x01(\x02H\x02\x88\x01\x01\x12\x10\n\x03v_y\x18\x05 \x01(\x02H\x03\x88\x01\x01\x42\x06\n\x04_p_xB\x06\n\x04_p_yB\x06\n\x04_v_xB\x06\n\x04_v_y\"\x0c\n\nEmptyParam\"\x1c\n\x08Response\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x89\x02\n\x05Unary\x12-\n\x05Start\x12\x11.unary.EmptyParam\x1a\x0f.unary.Response\"\x00\x12,\n\x04Stop\x12\x11.unary.EmptyParam\x1a\x0f.unary.Response\"\x00\x12-\n\x05Pause\x12\x11.unary.EmptyParam\x1a\x0f.unary.Response\"\x00\x12\x39\n\x0c\x43reatePlanet\x12\x16.unary.CreateBodyParam\x1a\x0f.unary.Response\"\x00\x12\x39\n\x0cUpdatePlanet\x12\x16.unary.UpdateBodyParam\x1a\x0f.unary.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bodies_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBODYPARAM._serialized_start=23
  _CREATEBODYPARAM._serialized_end=104
  _DELETEBODYPARAM._serialized_start=106
  _DELETEBODYPARAM._serialized_end=135
  _UPDATEBODYPARAM._serialized_start=138
  _UPDATEBODYPARAM._serialized_end=271
  _EMPTYPARAM._serialized_start=273
  _EMPTYPARAM._serialized_end=285
  _RESPONSE._serialized_start=287
  _RESPONSE._serialized_end=315
  _UNARY._serialized_start=318
  _UNARY._serialized_end=583
# @@protoc_insertion_point(module_scope)
